# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180303_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sponsor',
            field=models.CharField(default=2, max_length=20, verbose_name='sponsor'),
            preserve_default=False,
        ),
    ]
