# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_news_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sponsor',
            field=models.CharField(default='SPONSOR', max_length=20, verbose_name='sponsor'),
        ),
    ]
