# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-04 07:49
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_news_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
