# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADLINK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('link_value', models.CharField(max_length=200)),
                ('link_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ICO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_pic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('proj_desc', models.CharField(max_length=200)),
                ('movie_url', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('whitepaper_url', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=200)),
                ('token_type', models.CharField(max_length=20)),
                ('token_price', models.CharField(max_length=200)),
                ('token_sale_open', models.DateField()),
                ('token_sale_close', models.DateField()),
                ('fundraising_goal', models.CharField(max_length=200)),
                ('total_tokens', models.CharField(max_length=200)),
                ('available_token_sale', models.CharField(max_length=20)),
                ('not_participate', models.CharField(max_length=200)),
                ('min_max_person_cap', models.CharField(max_length=200)),
                ('token_distribution', models.CharField(max_length=200)),
                ('accepts', models.CharField(max_length=200)),
                ('bonus', models.CharField(max_length=200)),
                ('pre_sale', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_option', models.CharField(max_length=200)),
                ('review_option_value', models.CharField(max_length=200)),
                ('ico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICO')),
            ],
        ),
        migrations.CreateModel(
            name='SCREEN_SHOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(max_length=200)),
                ('ico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICO')),
            ],
        ),
        migrations.AddField(
            model_name='adlink',
            name='ico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICO'),
        ),
    ]
