# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atsd_name', models.CharField(max_length=200)),
                ('atsd_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ico',
            name='accepts',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='available_token_sale',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='min_max_person_cap',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='not_participate',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='pre_sale',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='token_distribution',
        ),
        migrations.AddField(
            model_name='atsd',
            name='ico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICO'),
        ),
    ]
