# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180209_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='ico',
            name='accepts',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
