# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ico_accepts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adlink',
            options={'verbose_name': 'Additional Link'},
        ),
        migrations.AlterModelOptions(
            name='atsd',
            options={'verbose_name': 'Additional Token Sale Detail'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review'},
        ),
        migrations.AlterModelOptions(
            name='screen_shot',
            options={'verbose_name': 'Screen Shot'},
        ),
        migrations.AddField(
            model_name='screen_shot',
            name='specifications',
            field=models.FileField(default=django.utils.timezone.now, upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
