# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180226_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen_shot',
            name='specifications',
        ),
    ]
