# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_screen_shot_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen_shot',
            name='specifications',
            field=models.FileField(default=datetime.datetime(2018, 2, 28, 0, 49, 5, 506975, tzinfo=utc), upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
