# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_screen_shot_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen_shot',
            name='specifications',
            field=models.FileField(upload_to='ico_proj_static/ScreenShots'),
        ),
    ]
