# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180227_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen_shot',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='screen_shot',
            name='pic_url',
            field=models.FileField(upload_to='ScreenShots'),
        ),
    ]
