# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180227_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='ico',
            name='interest',
            field=models.CharField(choices=[('NR', 'Not Rated'), ('Neu', 'Neutral'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('S', 'Sponsored')], default='NR', max_length=10),
        ),
        migrations.AddField(
            model_name='ico',
            name='market',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
