# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180301_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlink',
            name='link_type',
            field=models.CharField(choices=[('not social', 'not social'), ('social', 'social')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ico',
            name='interest',
            field=models.CharField(choices=[('Not Rated', 'Not Rated'), ('Neutral', 'Neutral'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Sponsored', 'Sponsored')], default='Not Rated', max_length=10),
        ),
    ]
