# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180303_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_pic', models.FileField(upload_to='Logos')),
                ('text', models.CharField(max_length=200)),
                ('url_button', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Advertise',
            },
        ),
    ]
